import { motion } from "framer-motion";
import {
  Download,
  Eye,
  FileText,
} from "lucide-react";

export default function ReportsTable({
  reports,
  onPreview,
  onDownload,
}) {
  const getStatusStyle = (status) => {
    switch (status) {
      case "Completed":
        return "bg-emerald-500/15 text-emerald-400 border border-emerald-500/20";

      case "Generating":
        return "bg-yellow-500/15 text-yellow-400 border border-yellow-500/20";

      case "Failed":
        return "bg-red-500/15 text-red-400 border border-red-500/20";

      default:
        return "bg-gray-500/15 text-gray-300 border border-gray-500/20";
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-[#111827] shadow-xl"
    >
      <div className="border-b border-white/10 p-6">
        <h2 className="text-xl font-semibold text-white">
          Reports Library
        </h2>

        <p className="mt-1 text-sm text-gray-400">
          Browse, preview and download generated reports.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full">
          <thead className="bg-[#1f2937]">
            <tr>
              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300">
                Report
              </th>

              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300">
                Type
              </th>

              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300">
                Generated By
              </th>

              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300">
                Date
              </th>

              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300">
                Status
              </th>

              <th className="px-6 py-4 text-center text-sm font-semibold text-gray-300">
                Actions
              </th>
            </tr>
          </thead>

          <tbody>
            {reports.map((report) => (
              <tr
                key={report.id}
                className="border-t border-white/5 transition hover:bg-white/5"
              >
                <td className="px-6 py-5">
                  <div className="flex items-center gap-3">
                    <div className="rounded-xl bg-cyan-500/10 p-3">
                      <FileText
                        className="text-cyan-400"
                        size={20}
                      />
                    </div>

                    <div>
                      <p className="font-medium text-white">
                        {report.name}
                      </p>

                      <p className="text-xs text-gray-500">
                        Report ID #{report.id}
                      </p>
                    </div>
                  </div>
                </td>

                <td className="px-6 py-5 text-gray-300">
                  {report.type}
                </td>

                <td className="px-6 py-5 text-gray-300">
                  {report.createdBy}
                </td>

                <td className="px-6 py-5 text-gray-300">
                  {report.date}
                </td>

                <td className="px-6 py-5">
                  <span
                    className={`rounded-full px-3 py-1 text-xs font-semibold ${getStatusStyle(
                      report.status
                    )}`}
                  >
                    {report.status}
                  </span>
                </td>

                <td className="px-6 py-5">
                  <div className="flex items-center justify-center gap-3">
                    <button
                      onClick={() => onPreview(report)}
                      className="rounded-xl bg-cyan-500/10 p-2 text-cyan-400 transition hover:bg-cyan-500 hover:text-white"
                    >
                      <Eye size={18} />
                    </button>

                    <button
                      onClick={() => onDownload(report)}
                      className="rounded-xl bg-emerald-500/10 p-2 text-emerald-400 transition hover:bg-emerald-500 hover:text-white"
                    >
                      <Download size={18} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}

            {reports.length === 0 && (
              <tr>
                <td
                  colSpan={6}
                  className="py-12 text-center text-gray-400"
                >
                  No reports found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </motion.div>
  );
}