import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import {
  FileText,
  Sparkles,
  Calendar,
  User,
  ListChecks,
  ExternalLink,
} from "lucide-react";

export default function ReportPreview({ report }) {
  if (!report) {
    return (
      <div className="mt-8 rounded-3xl border border-dashed border-white/10 bg-[#111827] p-12 text-center">
        <FileText
          size={48}
          className="mx-auto mb-4 text-gray-500"
        />

        <h2 className="text-xl font-semibold text-white">
          Report Preview
        </h2>

        <p className="mt-2 text-gray-400">
          Select a report from the table to preview its details.
        </p>
      </div>
    );
  }

  const narrative = report.contentJson?.narrative;
  const recommendedActions = report.contentJson?.recommendedActions || [];

  return (
    <motion.div
      key={report.id}
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      className="mt-8 rounded-3xl border border-white/10 bg-[#111827] p-6 shadow-xl"
    >
      <div className="mb-6 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="rounded-2xl bg-linear-to-br from-cyan-500 to-emerald-500 p-4">
            <FileText
              className="text-white"
              size={28}
            />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white">
              {report.name}
            </h2>

            <p className="text-gray-400">
              Report Preview
            </p>
          </div>
        </div>

        <Link
          to={`/reports/${report.id}`}
          className="flex shrink-0 items-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-2.5 text-sm font-medium text-cyan-400 transition hover:bg-cyan-500 hover:text-white"
        >
          <ExternalLink size={16} />
          Open Full Report
        </Link>
      </div>

      <div className="grid gap-5 md:grid-cols-3">
        <div className="rounded-2xl bg-[#1f2937] p-5">
          <div className="mb-3 flex items-center gap-2">
            <Calendar
              className="text-cyan-400"
              size={18}
            />

            <span className="text-sm text-gray-400">
              Generated Date
            </span>
          </div>

          <p className="font-semibold text-white">
            {report.date}
          </p>
        </div>

        <div className="rounded-2xl bg-[#1f2937] p-5">
          <div className="mb-3 flex items-center gap-2">
            <User
              className="text-cyan-400"
              size={18}
            />

            <span className="text-sm text-gray-400">
              Generated By
            </span>
          </div>

          <p className="font-semibold text-white">
            {report.createdBy}
          </p>
        </div>

        <div className="rounded-2xl bg-[#1f2937] p-5">
          <div className="mb-3 flex items-center gap-2">
            <FileText
              className="text-cyan-400"
              size={18}
            />

            <span className="text-sm text-gray-400">
              File Type
            </span>
          </div>

          <p className="font-semibold text-white">
            {report.type}
          </p>
        </div>
      </div>

      <div className="mt-8 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-6">
        <div className="mb-4 flex items-center gap-2">
          <Sparkles
            className="text-cyan-400"
            size={20}
          />

          <h3 className="text-lg font-semibold text-white">
            AI Executive Summary
          </h3>
        </div>

        <p className="whitespace-pre-wrap leading-8 text-gray-300">
          {narrative || "This report doesn't have a generated narrative yet."}
        </p>
      </div>

      {recommendedActions.length > 0 && (
        <div className="mt-6 rounded-2xl border border-white/10 bg-[#1f2937] p-6">
          <div className="mb-4 flex items-center gap-2">
            <ListChecks
              className="text-emerald-400"
              size={20}
            />

            <h3 className="text-lg font-semibold text-white">
              Recommended Actions
            </h3>
          </div>

          <ul className="space-y-3">
            {recommendedActions.map((action, index) => (
              <li key={index} className="flex items-start gap-3 text-gray-300">
                <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-400" />
                <span className="leading-6">{action}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </motion.div>
  );
}