import api from "./api";

export async function getReportSummary() {
  const { data } = await api.get("/reports/summary");
  return data;
}

export async function getReports() {
  const { data } = await api.get("/reports");
  return data;
}

export async function generateReport(days = 7) {
  const { data } = await api.post("/reports/generate", { days });
  return data;
}

// Real PDF/Excel rendering isn't implemented yet — this exports the
// report's actual saved content (title, AI narrative, recommended
// actions) as a plain text file, so it's a genuine download of real
// data rather than a fake "success" alert.
export function downloadReport(report) {
  const lines = [
    report.name,
    `Type: ${report.type}`,
    `Generated: ${report.date}`,
    `Generated by: ${report.createdBy}`,
    "",
    "Summary:",
    report.contentJson?.narrative || "",
    "",
    "Recommended Actions:",
    ...(report.contentJson?.recommendedActions || []).map((a) => `- ${a}`),
  ];

  const blob = new Blob([lines.join("\n")], {
    type: "text/plain;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${report.name.replace(/\s+/g, "-")}.txt`;

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}