import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { toast } from "sonner";
import {
  ArrowLeft,
  Printer,
  FileText,
  Calendar,
  User,
  Sparkles,
  ListChecks,
  Quote,
} from "lucide-react";
import { getReportById } from "../services/reportsService";

export default function ReportDetail() {
  const { id } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      setLoading(true);
      try {
        const data = await getReportById(id);
        if (!cancelled) setReport(data);
      } catch (error) {
        if (!cancelled) {
          toast.error(error.response?.data?.message || "Could not load this report.");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [id]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[#081111] text-gray-400">
        Loading report...
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-[#081111] text-gray-400">
        <p>This report could not be found.</p>
        <Link to="/reports" className="text-cyan-400 hover:text-cyan-300">
          ← Back to Reports
        </Link>
      </div>
    );
  }

  const stats = report.contentJson?.stats;
  const narrative = report.contentJson?.narrative;
  const recommendedActions = report.contentJson?.recommendedActions || [];

  return (
    <div className="min-h-screen bg-[#081111] text-white">
      {/* Top bar — deliberately hidden when printing, so the PDF export
          via window.print() only contains the report content itself. */}
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#0B1212]/95 px-6 py-4 backdrop-blur print:hidden">
        <Link
          to="/reports"
          className="flex items-center gap-2 text-sm text-gray-300 transition hover:text-white"
        >
          <ArrowLeft size={18} />
          Back to Reports
        </Link>

        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-2.5 font-medium text-black transition hover:bg-cyan-400"
        >
          <Printer size={18} />
          Print / Save as PDF
        </button>
      </div>

      {/* Report content — this is the "shareable page": any workspace
          member with the URL can open it directly, and it's a clean
          printable document (browser's native Print → Save as PDF gives
          a real PDF export with zero extra dependencies). */}
      <div className="mx-auto max-w-4xl px-6 py-12 print:max-w-none print:px-0 print:py-0 print:text-black">
        <div className="mb-8 flex items-center gap-4">
          <div className="rounded-2xl bg-linear-to-br from-cyan-500 to-emerald-500 p-4 print:hidden">
            <FileText className="text-white" size={28} />
          </div>

          <div>
            <h1 className="text-3xl font-bold text-white print:text-black">
              {report.name}
            </h1>
            <p className="mt-1 text-gray-400 print:text-gray-600">
              Voice-of-Customer Report
            </p>
          </div>
        </div>

        <div className="mb-8 grid gap-4 sm:grid-cols-3">
          <InfoBlock icon={<Calendar size={16} />} label="Generated" value={report.date} />
          <InfoBlock icon={<User size={16} />} label="Generated By" value={report.createdBy} />
          <InfoBlock icon={<FileText size={16} />} label="Type" value={report.type} />
        </div>

        <Section title="Executive Summary" icon={<Sparkles size={18} />}>
          <p className="whitespace-pre-wrap leading-8 text-gray-300 print:text-black">
            {narrative || "No narrative available for this report."}
          </p>
        </Section>

        {recommendedActions.length > 0 && (
          <Section title="Recommended Actions" icon={<ListChecks size={18} />}>
            <ul className="space-y-3">
              {recommendedActions.map((action, i) => (
                <li
                  key={i}
                  className="flex items-start gap-3 text-gray-300 print:text-black"
                >
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-400 print:bg-black" />
                  {action}
                </li>
              ))}
            </ul>
          </Section>
        )}

        {stats?.topThemes?.length > 0 && (
          <Section title="Top Themes" icon={<FileText size={18} />}>
            <div className="space-y-2">
              {stats.topThemes.map((t) => (
                <div
                  key={t.name}
                  className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 py-3 print:border-gray-300 print:bg-transparent"
                >
                  <span className="text-gray-200 print:text-black">{t.name}</span>
                  <span className="text-sm text-gray-400 print:text-gray-600">
                    {t.count} mentions
                  </span>
                </div>
              ))}
            </div>
          </Section>
        )}

        {stats?.sampleQuotes?.length > 0 && (
          <Section title="Representative Quotes" icon={<Quote size={18} />}>
            <div className="space-y-3">
              {stats.sampleQuotes.map((q, i) => (
                <blockquote
                  key={i}
                  className="rounded-xl border-l-4 border-cyan-500 bg-white/5 p-4 text-gray-300 print:border-gray-400 print:bg-transparent print:text-black"
                >
                  &ldquo;{q.content}&rdquo;
                  <footer className="mt-2 text-xs text-gray-500 print:text-gray-600">
                    — {q.customerLabel || "Anonymous"}, via {q.channel}
                  </footer>
                </blockquote>
              ))}
            </div>
          </Section>
        )}

        {typeof stats?.pctNegative === "number" && (
          <Section title="Sentiment Snapshot" icon={<Sparkles size={18} />}>
            <p className="text-gray-300 print:text-black">
              {stats.totalItems} feedback item{stats.totalItems === 1 ? "" : "s"} in this
              period, {stats.pctNegative}% negative
              {typeof stats.sentimentDelta === "number" &&
                (stats.sentimentDelta > 0
                  ? `, negativity up ${stats.sentimentDelta} points versus the prior period.`
                  : stats.sentimentDelta < 0
                    ? `, negativity down ${Math.abs(stats.sentimentDelta)} points versus the prior period.`
                    : ", unchanged versus the prior period.")}
            </p>
          </Section>
        )}
      </div>
    </div>
  );
}

function InfoBlock({ icon, label, value }) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/5 p-4 print:border-gray-300 print:bg-transparent">
      <div className="mb-1 flex items-center gap-2 text-xs text-gray-500 print:text-gray-600">
        {icon}
        {label}
      </div>
      <p className="font-medium text-white print:text-black">{value}</p>
    </div>
  );
}

function Section({ title, icon, children }) {
  return (
    <div className="mb-8 print:break-inside-avoid">
      <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-cyan-400 print:text-black">
        {icon}
        {title}
      </h2>
      {children}
    </div>
  );
}